###Combination, Return a CombinationEntity and increment a Combination Generation Counter
POST http://localhost:8080/generate
Authorization: Bearer {{$dotenv SECRET}}
content-type: application/json

{
  "NumberOfInputs": 2
}